obj-m := sg16lan.o
KERNELVERSION=@KERNVER@
MODULEPATH=/lib/modules/$(KERNELVERSION)/kernel/drivers/net/sg16lan.ko
CFLAGS+=@CFLAGS@

sg16lan.ko: sg16lan.c
	make -C @KERNSRC@ SUBDIRS=$(PWD) modules


all: sg16lan.ko

install: sg16lan.ko
	make -C @KERNSRC@ SUBDIRS=$(PWD) modules_install
	install -m 744 sg16cfg /sbin
	cp ./firmware/sg16.bin @FW_PATH@/

clean:
	make -C @KERNSRC@ SUBDIRS=$(PWD) clean
